name: Manual Workflow Dispatch

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'A message to include in the workflow run'
        required: true
      Tags:
        description: 'A boolean input'
        required: false

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Log level: ${{ github.event.inputs.logLevel }}"
          echo "Tags: ${{ github.event.inputs.tags }}"
