name: Wendy's GitHub Actions Learning 
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
   workflow_dispatch:
      inputs:
         logLevels:
           description: 'Log level'
           required: true
           default: 'warning'
           type: choice
           options:
           - info
           - warning
           - debug
       tags:
         description: 'Scenario Tags'
         required: false
         type: boolean
       environment:
         descriptions: 'Environmentn to run tests against'
         type: environment
         required: true

jobs:
    log-inputs:
       runs-on: ubuntu-latest
       steps:
         - run:
              echo "Level $LEVEL"
              echo "Tags: $TAGS"
              echo " Environment ; $ENVIRONMENT" 
           env:
              LEVEL: ${{inputs.logLevel}}
              TAGS: ${{inputs.tags}}
              ENVIRONMENT: ${{inputs.environment}}
